const PREV_MESSAGES = 'PREV_MESSAGES';
const SEND_MESSAGE = 'SEND_MESSAGE';
const NEW_MESSAGE = 'NEW_MESSAGE';
const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const PREV_USERS = 'PREV_USERS';
const NEW_USER = 'NEW_USER';

module.exports = {
  PREV_MESSAGES,
  SEND_MESSAGE,
  NEW_MESSAGE,
  LOGIN,
  LOGOUT,
  PREV_USERS,
  NEW_USER,
};